# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish LMT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./

    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        pip install -r requirements.txt
        # pip install pylint
        pip install pyinstaller
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
    
    - run: npm ci
      working-directory: ./UI
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"

    - run: npm run build --if-present
      working-directory: ./UI 
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"

    - name: "Set up LMTServer"
      run: cmd.exe /c makefile.bat

    - run: npm run build-pub
      working-directory: ./UI
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
